export const ACTION = {
    SIGNIN_USER: "SIGNIN_USER",
    SIGNUP_USER: "SIGNUP_USER",
    LOGOUT_USER: "LOGOUT_USER",

    GET_PRODUCT: "GET_PRODUCT",
    CREATE_PRODUCT: "CREATE_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    
    ADD_CART: "ADD_CART",
    SET_CART: "SET_CART",
    DELETE_CART: "DELETE_CART",
    INCREASE_PRODUCT: "INCREASE_PRODUCT",
    DECREASE_PRODUCT: "DECREASE_PRODUCT",

    GET_ORDER: "GET_ORDER",
    ADD_ORDER: "ADD_ORDER",
};